//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPrj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerary_Plan行程計畫
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itinerary_Plan行程計畫()
        {
            this.Order訂單 = new HashSet<Order訂單>();
        }
    
        public int Itinerary_ID { get; set; }
        public string Itinerary_Name { get; set; }
        public short Itinerary_Days { get; set; }
        public System.DateTime Departure_Date { get; set; }
        public System.DateTime Inbound_Date { get; set; }
        public short Maximum_number_of_people { get; set; }
        public decimal Single_Journey_Price { get; set; }
        public string Itinerary_Describtion { get; set; }
        public int 旅遊類型ID { get; set; }
        public int 旅遊主題ID { get; set; }
        public string 介紹文章 { get; set; }
        public byte[] 圖片 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order訂單> Order訂單 { get; set; }
    }
}
